import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.symbol.KSClassDeclaration

fun UnitProcessor.processBasicUnitMath(resolver: Resolver) {
    // Find all classes with @JvmInline
    val symbols = resolver.getSymbolsWithAnnotation("kotlin.jvm.JvmInline")
        .filterIsInstance<KSClassDeclaration>()

    logger.warn("Faraday KSP: Found ${symbols.count()} symbols.")

    symbols.forEach { classDec ->
        val packageName = classDec.packageName.asString()
        val className = classDec.simpleName.asString()
        val parameterName = classDec.primaryConstructorParameterName()

        generateExtensions(packageName = packageName, className = className, parameterName = parameterName)
    }
}

private fun UnitProcessor.generateExtensions(packageName: String, className: String, parameterName: String) {
    val file = codeGenerator.createNewFile(
        Dependencies(aggregating = true), packageName, "${className}Operators"
    )

    fun operator(operation: Operation) = when (operation) {
        Operation.Plus, Operation.Minus -> """operator fun $className.${operation.operator}(other: $className): $className = $className($parameterName ${operation.symbol} other.$parameterName)"""
        Operation.Times, Operation.Div -> """operator fun $className.${operation.operator}(factor: Number): $className = $className($parameterName ${operation.symbol} factor.toDouble())"""
    }

    fun jvmName(operation: Operation) =
        """@JvmName("${className.replaceFirstChar { it.lowercase() }}${operation.name}")"""

    file.writer().use { writer ->
        val isJvm = platformName?.lowercase() == "jvm"

        writer.appendLine("package $packageName;")
        writer.appendLine()
        writer.appendLine("// Generated by Faraday KSP - Do not edit")
        writer.appendLine()

        writer.write(
            if (isJvm) {
                """
                import kotlin.jvm.JvmName
                
                ${jvmName(Operation.Plus)}
                ${operator(Operation.Plus)}
    
                ${jvmName(Operation.Minus)}
                ${operator(Operation.Minus)}
    
                ${jvmName(Operation.Times)}
                ${operator(Operation.Times)}
    
                ${jvmName(Operation.Div)}
                ${operator(Operation.Div)}
                """.trimIndent()
            } else {
                """
                ${operator(Operation.Plus)}
                ${operator(Operation.Minus)}
                ${operator(Operation.Times)}
                ${operator(Operation.Div)}
                """.trimIndent()
            }
        )
    }
}